name: Build For Windows

on:
  push:
    branches:
      - develop

jobs:
  build:
    #target/TemplateHelper.exe
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Build with Maven
        run: mvn package -Pwindows
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.1.0
        with:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            FROM_BRANCH: "develop"
            TO_BRANCH: "master"
      - name: Merge Pal
      - name: echo
        run: echo "something"