# This workflow will build a package using Maven and then release it when a tagged version is pushed

name: Create Release

on: 
 push:
  tags:
   - 'v*'

jobs:
  build:
#target/TemplateHelper.exe
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Build with Maven
      run: mvn package -Pwindows
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{github.ref}} 
        release_name: Release ${{github.ref}}
        body: |
         Changes in this release:
        draft: false
        prerelease: false 
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./target/TemplateHelper.exe
          asset_name: TemplateHelper.exe
          asset_content_type: application/vnd.microsoft.portable-executable
